version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn format
      - run: yarn tsc
      - run: yarn test:coverage
      - run: yarn test-d
      - run: yarn codecov -t $CODECOV_TOKEN
